version: "2"

services:

  prometheus:
    build: docker/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

  grafana:
    build: docker/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    #environment:
    #  - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus
    logging:
      driver: json-file
      options:
        max-size: "512k"
        max-file: "2"

volumes:

  prometheus-data: {}
  grafana-data: {}
